In [1]:
!git clone https://github.com/AlexeyAB/darknet

Cloning into 'darknet'...
remote: Enumerating objects: 15308, done.
remote: Counting objects: 100% (15308/15308), done.
remote: Compressing objects: 100% (4581/4581), done.
remote: Total 15308 (delta 10400), reused 15308 (delta 10400), pack-reused 0
Receiving objects: 100% (15308/15308), 13.70 MiB | 13.75 MiB/s, done.
Resolving deltas: 100% (10400/10400), done.


In [2]:
cd darknet

/content/darknet


In [3]:
ls

3rdparty/               darknet_video.py        net_cam_v4.sh*
build/                  data/                   README.md
build.ps1*              image_yolov3.sh*        results/
cfg/                    image_yolov4.sh*        scripts/
cmake/                  include/                src/
CMakeLists.txt          json_mjpeg_streams.sh*  vcpkg.json
DarknetConfig.cmake.in  LICENSE                 video_yolov3.sh*
darknet_images.py       Makefile                video_yolov4.sh*
darknet.py              net_cam_v3.sh*


In [4]:
#Trabalhando com GPU, alterando o makefile
!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile

In [5]:
#testando se está com gpu 
import tensorflow as tf
device_name = tf.test.gpu_device_name()
print(device_name)

/device:GPU:0


In [6]:
!make

mkdir -p ./obj/
mkdir -p backup
chmod +x *.sh
g++ -std=c++11 -std=c++11 -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv4 2> /dev/null || pkg-config --cflags opencv` -DGPU -I/usr/local/cuda/include/ -DCUDNN -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC -Ofast -DOPENCV -DGPU -DCUDNN -I/usr/local/cudnn/include -c ./src/image_opencv.cpp -o obj/image_opencv.o
./src/image_opencv.cpp: In function ‘void draw_detections_cv_v3(void**, detection*, int, float, char**, image**, int, int)’:
./src/image_opencv.cpp:946:23: warning: variable ‘rgb’ set but not used [-Wunused-but-set-variable]
                 float rgb[3];
                       ^~~
./src/image_opencv.cpp: In function ‘void draw_train_loss(char*, void**, int, float, float, int, int, float, int, char*, float, int, int, double)’:
./src/image_opencv.cpp:1147:13: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
             if (iteration_old == 0)
             ^~
./src/image_

In [7]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [8]:
#Modelo pré-treinado com o COCO dataset
!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights

--2021-09-28 11:34:40--  https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github-releases.githubusercontent.com/75388965/ba4b6380-889c-11ea-9751-f994f5961796?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20210928%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210928T113440Z&X-Amz-Expires=300&X-Amz-Signature=42b500e3f398583246b430722f6a22ef91d16271a3b40b92e8acef0a400292dd&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=75388965&response-content-disposition=attachment%3B%20filename%3Dyolov4.weights&response-content-type=application%2Foctet-stream [following]
--2021-09-28 11:34:40--  https://github-releases.githubusercontent.com/75388965/ba4b6380-889c-11ea-9751-f994f5961796?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJ

In [9]:
!cp /content/gdrive/MyDrive/YoloRecursos/videos/video_teste02.mp4 ./

In [10]:
ls

3rdparty/               darknet_video.py        README.md
backup/                 data/                   results/
build/                  image_yolov3.sh*        scripts/
build.ps1*              image_yolov4.sh*        src/
cfg/                    include/                vcpkg.json
cmake/                  json_mjpeg_streams.sh*  video_teste02.mp4
CMakeLists.txt          LICENSE                 video_yolov3.sh*
darknet*                Makefile                video_yolov4.sh*
DarknetConfig.cmake.in  net_cam_v3.sh*          yolov4.weights
darknet_images.py       net_cam_v4.sh*
darknet.py              obj/


DETECTANDO

In [11]:
#parametro -dont_show para não rodar em tempo real o vídeo, pq o colab n permite
#parametro -i 0, para salvar o resultado
!./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights -dont_show video_teste02.mp4 -i 0 -out_filename video_teste02Resultado.avi

Streaming output truncated to the last 5000 lines.
traffic light: 38% 
traffic light: 27% 
truck: 53% 
car: 61% 
truck: 31% 
car: 100% 
car: 100% 
car: 96% 
car: 94% 
car: 93% 
car: 93% 
car: 92% 
car: 85% 
car: 44% 

FPS:7.7 	 AVG_FPS:7.7

 cvWriteFrame 
Objects:

traffic light: 97% 
traffic light: 92% 
traffic light: 56% 
traffic light: 32% 
truck: 61% 
car: 53% 
truck: 31% 
car: 88% 
car: 100% 
car: 100% 
car: 97% 
car: 97% 
car: 94% 
car: 94% 
car: 86% 
car: 50% 
car: 28% 

FPS:7.7 	 AVG_FPS:7.7

 cvWriteFrame 
Objects:

traffic light: 97% 
traffic light: 93% 
traffic light: 64% 
traffic light: 44% 
truck: 58% 
car: 52% 
car: 100% 
car: 100% 
car: 98% 
car: 97% 
car: 97% 
car: 96% 
car: 95% 
car: 91% 
car: 39% 

FPS:7.7 	 AVG_FPS:7.7

 cvWriteFrame 
Objects:

traffic light: 97% 
traffic light: 93% 
traffic light: 64% 
traffic light: 44% 
truck: 58% 
car: 51% 
car: 100% 
car: 100% 
car: 98% 
car: 97% 
car: 97% 
car: 96% 
car: 95% 
car: 91% 
car: 39% 

FPS:7.7 	 AVG_FPS:7.7

 cvWrite

In [12]:
!du -h video_teste02Resultado.avi

32M	video_teste02Resultado.avi


In [13]:
#Para ver, você pode baixar ou salvar no drive
!cp video_teste02Resultado.avi /content/gdrive/MyDrive/YoloRecursos/videos/

TESTANDO COM OUTRO VÍDEO E COM O PARAMETRO THRESHOLD

In [ ]:
!cp /content/gdrive/MyDrive/YoloRecursos/videos/video_rua01.mp4 ./

In [ ]:
#parametro -dont_show para não rodar em tempo real o vídeo, pq o colab n permite
#parametro -i 0, para salvar o resultado
!./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights -dont_show video_rua01.mp4 -out_filename video_rua01Resultado.avi -threshold 0.3

Streaming output truncated to the last 5000 lines.
person: 78% 
person: 48% 
person: 43% 
person: 34% 

FPS:8.1 	 AVG_FPS:8.0

 cvWriteFrame 
Objects:

handbag: 52% 
traffic light: 44% 
car: 99% 
car: 97% 
person: 100% 
person: 99% 
person: 98% 
person: 96% 
person: 95% 
person: 95% 
person: 93% 
person: 81% 
person: 77% 
person: 51% 
person: 50% 
person: 42% 

FPS:8.1 	 AVG_FPS:8.0

 cvWriteFrame 
Objects:

handbag: 32% 
traffic light: 42% 
car: 99% 
car: 97% 
person: 100% 
person: 99% 
person: 98% 
person: 98% 
person: 95% 
person: 95% 
person: 95% 
person: 74% 
person: 69% 
person: 58% 
person: 48% 
person: 47% 
person: 47% 
person: 42% 
person: 36% 

FPS:8.2 	 AVG_FPS:8.0

 cvWriteFrame 
Objects:

handbag: 27% 
traffic light: 45% 
car: 98% 
car: 97% 
car: 29% 
person: 100% 
person: 98% 
person: 98% 
person: 98% 
person: 98% 
person: 96% 
person: 95% 
person: 95% 
person: 77% 
person: 75% 
person: 59% 
person: 57% 
person: 44% 
person: 41% 

FPS:8.2 	 AVG_FPS:8.0

 cvWriteFrame 
Obj

In [ ]:
!cp video_rua01Resultado.avi /content/gdrive/MyDrive/YoloRecursos/videos/

OPENCV EM VÍDEOS

In [ ]:
!pip install opencv-python==4.4.0.40

import cv2
import numpy as np
import time
import os
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
import zipfile



     |████████████████████████████████| 49.4 MB 60 kB/s 
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.1.2.30
    Uninstalling opencv-python-4.1.2.30:
      Successfully uninstalled opencv-python-4.1.2.30
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.


In [ ]:
cd content/


/content


In [ ]:
path = '/content/gdrive/MyDrive/YoloRecursos/modeloYoloV4.zip'
zipObject = zipfile.ZipFile(file=path,mode='r')

zipObject.extractall('./')
zipObject.close()

In [ ]:
labelsPath = os.path.sep.join(['/content/cfg', 'coco.names'])
labelsPath

LABELS = open(labelsPath).read().strip().split('\n')
LABELS

['person',
 'bicycle',
 'car',
 'motorbike',
 'aeroplane',
 'bus',
 'train',
 'truck',
 'boat',
 'traffic light',
 'fire hydrant',
 'stop sign',
 'parking meter',
 'bench',
 'bird',
 'cat',
 'dog',
 'horse',
 'sheep',
 'cow',
 'elephant',
 'bear',
 'zebra',
 'giraffe',
 'backpack',
 'umbrella',
 'handbag',
 'tie',
 'suitcase',
 'frisbee',
 'skis',
 'snowboard',
 'sports ball',
 'kite',
 'baseball bat',
 'baseball glove',
 'skateboard',
 'surfboard',
 'tennis racket',
 'bottle',
 'wine glass',
 'cup',
 'fork',
 'knife',
 'spoon',
 'bowl',
 'banana',
 'apple',
 'sandwich',
 'orange',
 'broccoli',
 'carrot',
 'hot dog',
 'pizza',
 'donut',
 'cake',
 'chair',
 'sofa',
 'pottedplant',
 'bed',
 'diningtable',
 'toilet',
 'tvmonitor',
 'laptop',
 'mouse',
 'remote',
 'keyboard',
 'cell phone',
 'microwave',
 'oven',
 'toaster',
 'sink',
 'refrigerator',
 'book',
 'clock',
 'vase',
 'scissors',
 'teddy bear',
 'hair drier',
 'toothbrush']

In [ ]:
weightsPath = os.path.sep.join(['/content', 'yolov4.weights'])
configPath = os.path.sep.join(['/content/cfg', 'yolov4.cfg'])

In [ ]:
#Criando a rede neural
net = cv2.dnn.readNet(configPath, weightsPath)
net

<dnn_Net 0x7f2952a2d070>

In [ ]:
#Definindo mais configurações para a detecção
#Criando uma cor para cada classe do COCO definido em LABELS
np.random.seed(42)
COLORS = np.random.randint(0,255, size=(len(LABELS), 3), dtype='uint8')
print(COLORS)

[[102 220 225]
 [ 95 179  61]
 [234 203  92]
 [  3  98 243]
 [ 14 149 245]
 [ 46 106 244]
 [ 99 187  71]
 [212 153 199]
 [188 174  65]
 [153  20  44]
 [203 152 102]
 [214 240  39]
 [121  24  34]
 [114 210  65]
 [239  39 214]
 [244 151  25]
 [ 74 145 222]
 [ 14 202  85]
 [145 117  87]
 [184 189 221]
 [116 237 109]
 [ 85  99 172]
 [226 153 103]
 [235 146  36]
 [151  62  68]
 [181 130 160]
 [160 166 149]
 [  6  69   5]
 [ 52 253 112]
 [ 14   1   3]
 [ 76 248  87]
 [233 212 184]
 [235 245  26]
 [213 157 253]
 [ 68 240  37]
 [219  91  54]
 [129   9  51]
 [  0 191  20]
 [140  46 187]
 [147   1 254]
 [ 20 153 243]
 [ 46 160  68]
 [ 19 158 203]
 [209 226  77]
 [ 57  77 149]
 [156  21 112]
 [ 86 134 252]
 [ 24 207   1]
 [235 242 147]
 [110  88 107]
 [231   5  48]
 [254 141  74]
 [218 161  87]
 [134  58 100]
 [162 156 254]
 [ 73  93 102]
 [169 222 181]
 [ 35  71 242]
 [ 11 219 253]
 [201  74 187]
 [ 10  72 249]
 [207 227 201]
 [ 93  14 231]
 [150  59 189]
 [  0 193 116]
 [189 251  49]
 [ 23 174 

In [ ]:
ln = net.getLayerNames()
print('Todas as camadas')
print(ln)
print('TOTAL DE CAMADAS DO MODELO: '+ str(len(ln)))
print('Camadas de saída')
print(net.getUnconnectedOutLayers())
#Lista de camadas de saída
ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]
print(ln)

Todas as camadas
['conv_0', 'bn_0', 'mish_1', 'conv_1', 'bn_1', 'mish_2', 'conv_2', 'bn_2', 'mish_3', 'identity_3', 'conv_4', 'bn_4', 'mish_5', 'conv_5', 'bn_5', 'mish_6', 'conv_6', 'bn_6', 'mish_7', 'shortcut_7', 'conv_8', 'bn_8', 'mish_9', 'concat_9', 'conv_10', 'bn_10', 'mish_11', 'conv_11', 'bn_11', 'mish_12', 'conv_12', 'bn_12', 'mish_13', 'identity_13', 'conv_14', 'bn_14', 'mish_15', 'conv_15', 'bn_15', 'mish_16', 'conv_16', 'bn_16', 'mish_17', 'shortcut_17', 'conv_18', 'bn_18', 'mish_19', 'conv_19', 'bn_19', 'mish_20', 'shortcut_20', 'conv_21', 'bn_21', 'mish_22', 'concat_22', 'conv_23', 'bn_23', 'mish_24', 'conv_24', 'bn_24', 'mish_25', 'conv_25', 'bn_25', 'mish_26', 'identity_26', 'conv_27', 'bn_27', 'mish_28', 'conv_28', 'bn_28', 'mish_29', 'conv_29', 'bn_29', 'mish_30', 'shortcut_30', 'conv_31', 'bn_31', 'mish_32', 'conv_32', 'bn_32', 'mish_33', 'shortcut_33', 'conv_34', 'bn_34', 'mish_35', 'conv_35', 'bn_35', 'mish_36', 'shortcut_36', 'conv_37', 'bn_37', 'mish_38', 'conv_38

In [ ]:
def mostrar(imagem):
  fig = plt.gcf()
  fig.set_size_inches(16,10)
  plt.axis('off')
  plt.imshow(cv2.cvtColor(imagem, cv2.COLOR_BGR2RGB))
  plt.show()

In [ ]:
layer_outputs = []
def blobImagem(net, imagem, mostrarTexto = True):
  inicio = time.time()

  blob = cv2.dnn.blobFromImage(imagem, 1 / 255.0, (416,416), swapRB=True, crop=False )
  net.setInput(blob)
  layer_outputs = net.forward(ln)

  fim = time.time()

  if mostrarTexto:
    print('YOLO levou {:.2f} segundos'.format( fim - inicio))
  
  return net, imagem, layer_outputs

In [ ]:
threshold = 0.5
#NMS - Non-Max Supression. 0.3 equivale a 30%
threshold_NMS = 0.3
bounding_boxes = []
confiances = []
idClasses = []
def deteccoes(detection, threshold, bounding_boxes, confiances, idClasses):
    scores = detection[5:]
    classeID = np.argmax(scores)
    confiance = scores[classeID]

    if confiance > threshold:
        #print('scores: '+ str(scores))
        #print('classe mais provável: '+ str(classeID))
        #print('confiança: '+ str(confiance))

        #Coordenadas da caixa
        caixa = detection[0:4] * np.array([W, H, W, H])
        (centerX, centerY, width, height) = caixa.astype('int')

        x = int(centerX - (width / 2 ))
        y = int(centerY - (height / 2 ))

        bounding_boxes.append([x, y, int(width), int(height)])
        confiances.append(float(confiance))
        idClasses.append(classeID)
    return bounding_boxes, confiances, idClasses

In [ ]:
def funcoesImagem(imagem, i, confiances, bounding_boxes, COLORS, LABELS, mostrarTexto=True):
  (x, y) = (bounding_boxes[i][0], bounding_boxes[i][1]) 
  (w, h) = (bounding_boxes[i][2], bounding_boxes[i][3])

  #objeto = imagemCP[y:y + h, x:x + w]
  #cv2_imshow(objeto)

  cor = [int(c) for c in COLORS[ idClasses[i] ] ]
  
  fundo = np.full((imagem.shape), (0,0,0), dtype=np.uint8 )
  texto = "{}: {:.4f}".format(LABELS[idClasses[i]], confiances[i])
  
  cv2.putText(fundo, texto, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255,255,255), 2 )

  fx, fy, fw, fh = cv2.boundingRect(fundo[:,:,2])

  cv2.rectangle(imagem, (x, y), (x+w,y+h), cor, 2 )

  cv2.rectangle(imagem, (fx, fy), (fx+fw, fy+fh), cor, -1)
  cv2.rectangle(imagem, (fx, fy), (fx+fw, fy+fh), cor, 3)
  cv2.rectangle(imagem, (fx, fy), (fx+fw, fy+fh), cor, -1)

  cv2.putText(imagem, texto, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,0), 1)
  if mostrarTexto:
    print('> '+texto)

  

  return imagem,x,y,w,h

In [ ]:
!cp /content/gdrive/MyDrive/YoloRecursos/videos/video_pessoas01.mp4 ./

In [ ]:
arquivoVideo = 'video_pessoas01.mp4'
captura = cv2.VideoCapture(arquivoVideo)
conectado, video = captura.read()

conectado

True

In [ ]:
video.shape

(720, 1280, 3)

In [ ]:
videoLargura = video.shape[1]
videoAltura = video.shape[0]
videoAltura, videoLargura

(720, 1280)

In [ ]:
def redimensionar(largura, altura, larguraMaxima=600):
  if largura > larguraMaxima:
    #mantendo a proporção
    proporcao = video.shape[1] / video.shape[0]
    videoLargura = larguraMaxima 
    videoAltura = int(videoLargura/ proporcao)
  else:
    videoLargura = largura
    videoAltura = altura

  return videoLargura, videoAltura

In [ ]:
videoAltura, videoLargura = redimensionar(videoLargura, videoAltura)
videoAltura, videoLargura

(337, 600)

In [ ]:
nomeArquivo = 'video_pessoas01Resultado.mp4'
#XVID é relacionado ao codec usado para salvar o dado. 
#fourcc é um código de 4 bits, para especificar o codec
#Se fosse salvar um video em mp4, o codec seria MP4V
fourcc = cv2.VideoWriter_fourcc(*'XVID')

In [ ]:
fps = 24


In [ ]:
saidaVideo = cv2.VideoWriter(nomeArquivo, fourcc, fps, (videoLargura, videoAltura))

In [ ]:
fontePequena, fonteMedia = 0.4, 0.6
fonte = cv2.FONT_HERSHEY_SIMPLEX

In [ ]:
amostrarExibir = 20
amostraAtual = 0


In [ ]:
while cv2.waitKey(1) < 0:
  conectado, frame = captura.read()

  if not conectado:
    break
  t = time.time()
  frame = cv2.resize(frame, (videoLargura, videoAltura))

  try:
    (H, W) = frame.shape[:2]
  except:
    print('erro')
    continue
  
  imagemCP = frame.copy()
  net, frame, layer_outputs = blobImagem(net, frame)

  bounding_boxes = []
  confiances = []
  idClasses = [] 
  for output in layer_outputs:
    for detection in output:
      bounding_boxes, confiances, idClasses = deteccoes(detection, threshold, bounding_boxes, confiances, idClasses)

  objs = cv2.dnn.NMSBoxes(bounding_boxes, confiances, threshold, threshold_NMS) 

  if len(objs) > 0:
    for i in objs.flatten():
      frame, x, y, w, h = funcoesImagem(frame, i, confiances, bounding_boxes, COLORS, LABELS)
      #objeto = imagemCP[y:y + h, x:x + w]
    
  cv2.putText(frame, 'Frame processado em {:.2f} segundos'.format(time.time()-t),
              (20, videoAltura-20), fonte, fontePequena, (250, 250, 250), 0, lineType=cv2.LINE_AA )
  
  if amostraAtual <= amostrarExibir:
    cv2_imshow(frame)
    amostraAtual += 1

  saidaVideo.write(frame)

print('terminou...')
saidaVideo.release()

cv2.destroyAllWindows()

terminou...


In [ ]:
!du -h video_pessoas01Resultado.mp4

14M	video_pessoas01Resultado.mp4


In [ ]:
!cp /content/video_pessoas01Resultado.mp4 /content/gdrive/MyDrive/YoloRecursos/videos